# -*- coding: utf-8 -*-
"""RANDOM FOREST.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MEv9QDbxaw-kPECvLa21-rhFm4tTI8AJ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as splt
import seaborn

df=pd.read_csv('esc_chat - Sheet1.csv')

df

x=df.drop(['Result'],axis=1)

x

y=df['Result']

y

from sklearn.preprocessing import LabelEncoder

Le_x=LabelEncoder()

x=x.apply(LabelEncoder().fit_transform)

x

from sklearn.model_selection import train_test_split

xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=.25,random_state=1)

from sklearn.ensemble import RandomForestClassifier

Rfc=RandomForestClassifier()

Rfc.fit(xtrain,ytrain)

Rfc.score(xtrain,ytrain)

"""# Cross Validation:"""

from sklearn.model_selection import cross_val_score

cv_score=cross_val_score(Rfc,x,y,cv=2)

cv_score

cv_score.mean()

"""# Confusion Matrix:"""

pred=Rfc.predict(xtest)

pred

from sklearn.metrics import confusion_matrix

confusion_matrix(ytest,pred)

from sklearn.metrics import classification_report

print(classification_report(ytest,pred))

